package net.sourceforge.taggerplugin.model;

/**
 *	Model object representing a single tag in the tag set.
 *
 * @author Christopher J. Stehno (chris@stehno.com)
 */
public class Tag {

	private long id;
	private String name, description;

	public Tag(){
		super();
	}

	public Tag(long id, String name, String description){
		this();
		this.id = id;
		this.name = name;
		this.description = description;
	}

	public String getDescription() {
		return(description);
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public long getId() {
		return(id);
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return(name);
	}

	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return("Tag: { id=" + id + ", name=[" + name + "], description=[" + description + "]}");
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		// NOTE: generated by Eclipse
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((this.description == null) ? 0 : this.description.hashCode());
		result = PRIME * result + (int) (this.id ^ (this.id >>> 32));
		result = PRIME * result + ((this.name == null) ? 0 : this.name.hashCode());
		return result;
	}

	/**
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		// NOTE: generated by Eclipse
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Tag other = (Tag) obj;
		if (this.description == null) {
			if (other.description != null)
				return false;
		} else if (!this.description.equals(other.description))
			return false;
		if (this.id != other.id)
			return false;
		if (this.name == null) {
			if (other.name != null)
				return false;
		} else if (!this.name.equals(other.name))
			return false;
		return true;
	}
}
